# Generated by Django 5.2.12 on 2026-04-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_scouting_only_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_products',
            field=models.BooleanField(default=False, help_text='Can access Products section'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_quotes',
            field=models.BooleanField(default=False, help_text='Can access Quotes section'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='access_scouting',
            field=models.BooleanField(default=False, help_text='Can access Scouting section'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='scouting_only',
            field=models.BooleanField(default=False, help_text='[Deprecated] Superseded by access_scouting'),
        ),
    ]
