# Generated by Django 4.2.18 on 2026-04-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0018_quote_hts_code_vendor_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
