# Generated by Django 4.2.18 on 2026-04-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_htscode_product_hts_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='htscode',
            name='category_hint',
            field=models.CharField(blank=True, choices=[('Audio Tech', 'Audio Tech'), ('Charging Tech', 'Charging Tech'), ('Drinkware', 'Drinkware'), ('Lanyards', 'Lanyards'), ('Mobile Tech', 'Mobile Tech'), ('Office Tech', 'Office Tech'), ('Personal Tech', 'Personal Tech'), ('USB Drives', 'USB Drives'), ('Other', 'Other')], help_text='Suggested product category for auto-suggest', max_length=50),
        ),
        migrations.AlterField(
            model_name='htscode',
            name='other_tariff_notes',
            field=models.TextField(blank=True, help_text='Notes on additional tariffs, exemptions, or conditions (e.g. copper content rules)'),
        ),
    ]
