# Generated by Django 5.2.12 on 2026-04-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_sourcing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Quote Only', 'Quote Only'), ('Open', 'Open'), ('Published', 'Published'), ('Canceled', 'Canceled')], default='Open', max_length=50),
        ),
    ]
